"""empty message

Revision ID: 935e090d07b1
Revises: 083394518e5f
Create Date: 2022-05-19 16:17:54.672504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935e090d07b1'
down_revision = '083394518e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column(
        'location', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'location')
    # ### end Alembic commands ###
